name: my_app
description: Custom Delivery Appp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  get_it: ^8.0.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  injectable: ^2.4.4
  intl: ^0.19.0
  json_serializable: ^6.8.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
